import type { CaseContent } from "./types";

export const caseEn: CaseContent = {
  eyebrow: "Results case",
  titleLead: "198 hours.",
  titleHighlight: "Done in 2 days.",
  subtitle:
    "How we structured more than 1,000 tasks in ClickUp for an environmental engineering company using Claude and Claude Code.",
  sector: "Environmental Engineering · ClickUp Implementation · AI + Automation",
  stats: [
    { value: "68", label: "services structured in ClickUp" },
    { value: "1,000+", label: "tasks created with a uniform standard" },
    { value: "-99%", label: "of the estimated time for manual execution" },
  ],
  phasesTitle: "How it was done",
  phases: [
    {
      title: "Strategic analysis with Claude",
      text: "The company's process documentation was loaded straight into Claude. It read, interpreted and suggested the ideal architecture in ClickUp: milestones, linked tasks and scalable hierarchies.",
    },
    {
      title: "Building at scale with Claude Code",
      text: "Python scripts generated by Claude created folders, lists, checklists and relationships through the ClickUp API. Each cycle was validated, adjusted and re-run until the delivery was right.",
    },
    {
      title: "Human direction and validation",
      text: "AI was the tool. Strategy, decisions and quality control were human, at every step of the process.",
    },
  ],
  resultsTitle: "Results for the client",
  results: [
    { strong: "Structured operation", rest: "ready to scale" },
    { strong: "Uniform standard", rest: "across all 68 services" },
    { strong: "Foundation ready", rest: "for future automations" },
    { strong: "Reusable scripts", rest: "for new projects" },
    { strong: "Zero rework", rest: "in the final delivery" },
  ],
  compareTitle: "Execution time",
  compare: [
    { label: "Manual", value: "~198h", percent: 100 },
    { label: "With ORDO", value: "2 days", percent: 2 },
  ],
  ctaText: "Your next project can look like this.",
  cta: "Talk to ORDO",
};
